from sqlalchemy import Column, Integer, Sequence, String, DateTime, Float, Enum
from sqlalchemy.ext.declarative import declarative_base
from app.constants import FileType
from app.db import Base


class RFIDCard(Base):
    """
    Represents an RFID card in the database.

    Attributes:
    card_id (Integer): A unique integer that serves as the primary key. This value is automatically generated by the database.
    rfid_code (String): A unique string that represents the RFID of the card, fixed by the manufacturer. This value must be unique across all RFID cards.
    writable_tag (String): A writable string that represents a tag on the RFID card. This value must be unique across all RFID cards.
    file_name (String): A string that represents the name of a file associated with the RFID card. This is the name the file will be stored under in object storage and the name it will have when downloaded to the local file system for usage.
    file_type (Enum): An enumerated type that can take the values 'audio', 'video', or 'image'. This represents the type of file associated with the RFID card.
    date (DateTime): A datetime that represents when the file was created or last modified.
    duration (Float): A float that represents the duration of the file in some unit of time. This could represent the length of an audio or video file, for example.
    size (Float): A float that represents the size of the file in some unit of measurement. This could represent the file size in bytes, for example.
    """

    __tablename__ = "rfid_cards"

    card_id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    rfid_code = Column(
        String,
        unique=True,
        index=True,
    )
    writable_tag = Column(
        String,
        unique=True,
        index=True,
    )
    file_name = Column(
        String,
    )
    file_type = Column(
        Enum(FileType),
    )
    date = Column(
        DateTime,
    )
    duration = Column(
        Float,
    )
    size = Column(
        Float,
    )
